"""Ground-truth BSP scene sampler.

Scenes are generated BY sampling a BSP region tree first (the tree is layout
sampler, renderer input, and parse-diagnostic label at once), then decorating
leaves with backgrounds / objects. The tree is constrained to the model
support of DESIGN.md §3:

- every cut lands on the 8-px grid with relative offset in [0.3, 0.7];
- leaf regions have both sides in {8, 16} px (any side > 16 must expand,
  8x8 must terminate);
- object cells are 16x16 leaves holding exactly one shape, fully inside the
  cell with >= 2 px margin — no overlap, no occlusion.

Tree JSON schema (serialized verbatim into meta.jsonl):
  internal node: {"rect": [x0,y0,x1,y1], "axis": "V"|"H", "cut": px,
                  "children": [lo, hi]}          # lo = left/top child
  leaf node:     {"rect": [x0,y0,x1,y1], "leaf": true, "obj": int|null,
                  "fill": [r,g,b]}               # optional "frame": true
Tier-3 frame region nodes additionally carry {"frame_color": name}.

Object schema: {"shape","color","size","texture": str, "rgb": [r,g,b],
                "cell": [x0,y0,x1,y1], "bbox": [x0,y0,x1,y1]}.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Iterator, List, Optional, Sequence, Tuple

import numpy as np

from .vocab import (
    BACKGROUNDS,
    BACKGROUND_NAMES,
    BG_JITTER,
    CANVAS,
    COLOR_JITTER,
    COLOR_NAMES,
    COLORS,
    GRID,
    HOLDOUT_COMBOS,
    MAX_LEAF,
    MIN_MARGIN,
    OFFSET_HI,
    OFFSET_LO,
    SHAPES,
    SIZE_NAMES,
    SIZES,
)

DEFAULT_TIER_MIX: Tuple[float, float, float, float] = (0.10, 0.30, 0.40, 0.20)

# termination probability for leaf-eligible regions in the generic grower
_TERM_P: Dict[Tuple[int, int], float] = {(16, 16): 0.75, (8, 16): 0.7, (16, 8): 0.7}
_MAX_TRIES = 200
_EPS = 1e-9


@dataclass
class Scene:
    """One procedural scene. All fields are JSON-able plain python."""

    idx: int
    tier: int
    tree: Dict[str, Any]
    objects: List[Dict[str, Any]]
    background: str  # background name; "sky|sand" for tier-2 sky/ground scenes
    relation: Optional[Dict[str, Any]] = None  # tier 1: {"type","a","b"}
    frame: Optional[Dict[str, Any]] = None  # tier 3: {"color","rgb","rect","inner"}


# --------------------------------------------------------------------------
# rng helpers
# --------------------------------------------------------------------------

def scene_rng(global_seed: int, idx: int) -> np.random.Generator:
    """The canonical per-sample rng stream: SeedSequence([global_seed, idx])."""
    return np.random.default_rng(np.random.SeedSequence([int(global_seed), int(idx)]))


def caption_rng(global_seed: int, idx: int) -> np.random.Generator:
    """Independent per-sample stream for caption template draws."""
    return np.random.default_rng(
        np.random.SeedSequence([int(global_seed), int(idx), 1])
    )


# --------------------------------------------------------------------------
# tree construction
# --------------------------------------------------------------------------

def _mk_leaf(rect: Sequence[int]) -> Dict[str, Any]:
    return {"rect": [int(v) for v in rect], "leaf": True, "obj": None, "fill": None}


def _mk_node(
    rect: Sequence[int], axis: str, cut: int, lo: Dict[str, Any], hi: Dict[str, Any]
) -> Dict[str, Any]:
    return {
        "rect": [int(v) for v in rect],
        "axis": axis,
        "cut": int(cut),
        "children": [lo, hi],
    }


def _split_rect(
    rect: Sequence[int], axis: str, cut: int
) -> Tuple[Tuple[int, int, int, int], Tuple[int, int, int, int]]:
    x0, y0, x1, y1 = rect
    if axis == "V":
        return (x0, y0, cut, y1), (cut, y0, x1, y1)
    return (x0, y0, x1, cut), (x0, cut, x1, y1)


def _valid_cuts(lo: int, hi: int) -> List[int]:
    """Grid cuts of interval [lo,hi) with relative offset in [0.3, 0.7]."""
    length = hi - lo
    out = []
    for j in range(1, length // GRID):
        t = j * GRID / length
        if OFFSET_LO - _EPS <= t <= OFFSET_HI + _EPS:
            out.append(lo + j * GRID)
    return out


def _grow(
    rng: np.random.Generator,
    rect: Tuple[int, int, int, int],
    force_axis: Optional[str] = None,
) -> Dict[str, Any]:
    """Sample a random in-support BSP subtree over `rect`.

    `force_axis` forces the root of this subtree to split on that axis
    (used for tier-2 sky/ground scenes).
    """
    x0, y0, x1, y1 = rect
    w, h = x1 - x0, y1 - y0
    leaf_ok = w <= MAX_LEAF and h <= MAX_LEAF
    if leaf_ok and force_axis is None:
        if (w == GRID and h == GRID) or rng.random() < _TERM_P[(w, h)]:
            return _mk_leaf(rect)
    axes = []
    if _valid_cuts(x0, x1):
        axes.append("V")
    if _valid_cuts(y0, y1):
        axes.append("H")
    if force_axis is not None:
        assert force_axis in axes, "forced axis has no valid cut"
        axes = [force_axis]
    axis = axes[int(rng.integers(len(axes)))]
    cuts = _valid_cuts(x0, x1) if axis == "V" else _valid_cuts(y0, y1)
    cut = cuts[int(rng.integers(len(cuts)))]
    rlo, rhi = _split_rect(rect, axis, cut)
    return _mk_node(rect, axis, cut, _grow(rng, rlo), _grow(rng, rhi))


def iter_leaves(node: Dict[str, Any]) -> Iterator[Dict[str, Any]]:
    """Yield leaf node dicts (mutable references) in depth-first lo-hi order."""
    if node.get("leaf"):
        yield node
    else:
        for child in node["children"]:
            for leaf in iter_leaves(child):
                yield leaf


def _object_cells(node: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Leaves big enough to hold an object (16x16, not frame cells)."""
    out = []
    for leaf in iter_leaves(node):
        x0, y0, x1, y1 = leaf["rect"]
        if x1 - x0 == MAX_LEAF and y1 - y0 == MAX_LEAF and not leaf.get("frame"):
            out.append(leaf)
    return out


# --------------------------------------------------------------------------
# attribute / placement helpers
# --------------------------------------------------------------------------

def _jitter(rgb: Sequence[int], rng: np.random.Generator, amt: int) -> List[int]:
    out = []
    for v in rgb:
        out.append(int(np.clip(int(v) + int(rng.integers(-amt, amt + 1)), 0, 255)))
    return out


def _sample_attrs(
    rng: np.random.Generator, exclude: Optional[set] = None
) -> Dict[str, str]:
    """Rejection-resample attributes so no holdout (color, shape) combo appears."""
    exclude = exclude or set()
    for _ in range(_MAX_TRIES):
        color = COLOR_NAMES[int(rng.integers(len(COLOR_NAMES)))]
        shape = SHAPES[int(rng.integers(len(SHAPES)))]
        if (color, shape) in HOLDOUT_COMBOS or (color, shape) in exclude:
            continue
        size = SIZE_NAMES[int(rng.integers(len(SIZE_NAMES)))]
        texture = "solid" if rng.random() < 0.4 else (
            ("striped", "dotted", "checker")[int(rng.integers(3))]
        )
        return {"shape": shape, "color": color, "size": size, "texture": texture}
    raise RuntimeError("attribute rejection loop exhausted")


def _place_object(
    rng: np.random.Generator,
    cell: Sequence[int],
    attrs: Dict[str, str],
    centered: bool = False,
) -> Dict[str, Any]:
    x0, y0, x1, y1 = (float(v) for v in cell)
    s = SIZES[attrs["size"]]
    w = s
    h = round(s * 0.62, 2) if attrs["shape"] == "rectangle" else s
    slack_x = (x1 - x0 - w) / 2.0 - MIN_MARGIN
    slack_y = (y1 - y0 - h) / 2.0 - MIN_MARGIN
    assert slack_x >= -_EPS and slack_y >= -_EPS, "object does not fit cell"
    cx = (x0 + x1) / 2.0
    cy = (y0 + y1) / 2.0
    if not centered:
        cx += float(rng.uniform(-max(slack_x, 0.0), max(slack_x, 0.0)))
        cy += float(rng.uniform(-max(slack_y, 0.0), max(slack_y, 0.0)))
    bbox = [
        round(cx - w / 2.0, 2),
        round(cy - h / 2.0, 2),
        round(cx + w / 2.0, 2),
        round(cy + h / 2.0, 2),
    ]
    return {
        "shape": attrs["shape"],
        "color": attrs["color"],
        "size": attrs["size"],
        "texture": attrs["texture"],
        "rgb": _jitter(COLORS[attrs["color"]], rng, COLOR_JITTER),
        "cell": [int(v) for v in cell],
        "bbox": bbox,
    }


def _apply_bg(tree: Dict[str, Any], bg_rgb: Sequence[int]) -> None:
    for leaf in iter_leaves(tree):
        if leaf["fill"] is None:
            leaf["fill"] = list(bg_rgb)


def _pick_bg(rng: np.random.Generator) -> Tuple[str, List[int]]:
    name = BACKGROUND_NAMES[int(rng.integers(len(BACKGROUND_NAMES)))]
    return name, _jitter(BACKGROUNDS[name], rng, BG_JITTER)


# --------------------------------------------------------------------------
# tier builders
# --------------------------------------------------------------------------

def _build_tier0(rng: np.random.Generator, idx: int) -> Scene:
    for _ in range(_MAX_TRIES):
        tree = _grow(rng, (0, 0, CANVAS, CANVAS))
        cells = _object_cells(tree)
        if cells:
            break
    else:  # pragma: no cover
        raise RuntimeError("tier0: no object cell after retries")
    c = CANVAS / 2.0
    cell = min(
        cells,
        key=lambda l: ((l["rect"][0] + l["rect"][2]) / 2 - c) ** 2
        + ((l["rect"][1] + l["rect"][3]) / 2 - c) ** 2,
    )
    obj = _place_object(rng, cell["rect"], _sample_attrs(rng), centered=True)
    cell["obj"] = 0
    bg_name, bg_rgb = _pick_bg(rng)
    _apply_bg(tree, bg_rgb)
    return Scene(idx=idx, tier=0, tree=tree, objects=[obj], background=bg_name)


def _build_tier1(rng: np.random.Generator, idx: int) -> Scene:
    for _ in range(_MAX_TRIES):
        tree = _grow(rng, (0, 0, CANVAS, CANVAS))
        cells_lo = _object_cells(tree["children"][0])
        cells_hi = _object_cells(tree["children"][1])
        if cells_lo and cells_hi:
            break
    else:  # pragma: no cover
        raise RuntimeError("tier1: no cells on both sides of root split")
    cell_a = cells_lo[int(rng.integers(len(cells_lo)))]
    cell_b = cells_hi[int(rng.integers(len(cells_hi)))]
    attrs_a = _sample_attrs(rng)
    attrs_b = _sample_attrs(rng, exclude={(attrs_a["color"], attrs_a["shape"])})
    obj_a = _place_object(rng, cell_a["rect"], attrs_a)
    obj_b = _place_object(rng, cell_b["rect"], attrs_b)
    cell_a["obj"] = 0
    cell_b["obj"] = 1
    relation = {"type": "left" if tree["axis"] == "V" else "above", "a": 0, "b": 1}
    bg_name, bg_rgb = _pick_bg(rng)
    _apply_bg(tree, bg_rgb)
    return Scene(
        idx=idx,
        tier=1,
        tree=tree,
        objects=[obj_a, obj_b],
        background=bg_name,
        relation=relation,
    )


def _build_tier2(rng: np.random.Generator, idx: int) -> Scene:
    n_obj = 3 + int(rng.integers(3))  # 3..5
    skyground = rng.random() < 0.5
    for _ in range(_MAX_TRIES):
        tree = _grow(
            rng, (0, 0, CANVAS, CANVAS), force_axis="H" if skyground else None
        )
        cells = _object_cells(tree)
        if len(cells) >= n_obj:
            break
    else:  # pragma: no cover
        raise RuntimeError("tier2: not enough object cells")
    order = rng.permutation(len(cells))[:n_obj]
    objects: List[Dict[str, Any]] = []
    used: set = set()
    for i, ci in enumerate(order):
        attrs = _sample_attrs(rng, exclude=used)
        used.add((attrs["color"], attrs["shape"]))
        cell = cells[int(ci)]
        objects.append(_place_object(rng, cell["rect"], attrs))
        cell["obj"] = i
    if skyground:
        cut = tree["cut"]
        sky_rgb = _jitter(BACKGROUNDS["sky"], rng, BG_JITTER)
        sand_rgb = _jitter(BACKGROUNDS["sand"], rng, BG_JITTER)
        for leaf in iter_leaves(tree):
            leaf["fill"] = list(sky_rgb) if leaf["rect"][3] <= cut else list(sand_rgb)
        bg_name = "sky|sand"
    else:
        bg_name, bg_rgb = _pick_bg(rng)
        _apply_bg(tree, bg_rgb)
    return Scene(idx=idx, tier=2, tree=tree, objects=objects, background=bg_name)


def _frame_region_tree(
    rng: np.random.Generator,
    rect: Tuple[int, int, int, int],
    frame_rgb: List[int],
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Decompose a 40x40 region into frame cells around one inner 16x16 cell.

    Per axis the strips are (16, 16, 8) or (8, 16, 16) so every cut keeps its
    relative offset in [0.3, 0.7]. Returns (subtree, inner_leaf_ref).
    """
    fx, fy, _, _ = rect

    def frame_leaf(r: Sequence[int]) -> Dict[str, Any]:
        leaf = _mk_leaf(r)
        leaf["frame"] = True
        leaf["fill"] = list(frame_rgb)
        return leaf

    def frame_subtree(r: Tuple[int, int, int, int]) -> Dict[str, Any]:
        sub = _grow(rng, r)
        for leaf in iter_leaves(sub):
            leaf["frame"] = True
            leaf["fill"] = list(frame_rgb)
        return sub

    f0x = 16 if rng.random() < 0.5 else 8
    f0y = 16 if rng.random() < 0.5 else 8
    ix0 = fx + f0x  # inner cell x range [ix0, ix0+16]
    iy0 = fy + f0y

    # middle vertical strip (16 wide, 40 tall) split along y into
    # top frame cell / inner object cell / bottom frame cell
    inner = _mk_leaf((ix0, iy0, ix0 + 16, iy0 + 16))
    top = frame_leaf((ix0, fy, ix0 + 16, iy0))
    bot = frame_leaf((ix0, iy0 + 16, ix0 + 16, fy + 40))
    strip_rect = (ix0, fy, ix0 + 16, fy + 40)
    if f0y == 16:
        lower = _mk_node((ix0, iy0, ix0 + 16, fy + 40), "H", iy0 + 16, inner, bot)
        mid = _mk_node(strip_rect, "H", iy0, top, lower)
    else:
        upper = _mk_node((ix0, fy, ix0 + 16, iy0 + 16), "H", iy0, top, inner)
        mid = _mk_node(strip_rect, "H", iy0 + 16, upper, bot)

    left = frame_subtree((fx, fy, ix0, fy + 40))
    right = frame_subtree((ix0 + 16, fy, fx + 40, fy + 40))
    if f0x == 16:
        rt = _mk_node((ix0, fy, fx + 40, fy + 40), "V", ix0 + 16, mid, right)
        node = _mk_node(rect, "V", ix0, left, rt)
    else:
        lt = _mk_node((fx, fy, ix0 + 16, fy + 40), "V", ix0, left, mid)
        node = _mk_node(rect, "V", ix0 + 16, lt, right)
    return node, inner


def _build_tier3(rng: np.random.Generator, idx: int) -> Scene:
    fx = 0 if rng.random() < 0.5 else 24
    fy = 0 if rng.random() < 0.5 else 24
    frect = (fx, fy, fx + 40, fy + 40)

    attrs = _sample_attrs(rng)
    frame_color = attrs["color"]
    while frame_color == attrs["color"]:
        frame_color = COLOR_NAMES[int(rng.integers(len(COLOR_NAMES)))]
    frame_rgb = _jitter(COLORS[frame_color], rng, COLOR_JITTER)

    frame_node, inner = _frame_region_tree(rng, frect, frame_rgb)
    frame_node["frame_color"] = frame_color
    obj = _place_object(rng, inner["rect"], attrs)
    inner["obj"] = 0

    # isolate the frame region from the canvas root: one V cut, one H cut
    # (in random order); both offsets (24/64, 40/64) are in [0.3, 0.7].
    def isolate(rect: Tuple[int, int, int, int], axis: str, inner_node: Dict) -> Dict:
        x0, y0, x1, y1 = rect
        if axis == "V":
            cut = fx + 40 if fx == 0 else fx
            (rl, rh) = _split_rect(rect, "V", cut)
            keep_lo = fx == 0
        else:
            cut = fy + 40 if fy == 0 else fy
            (rl, rh) = _split_rect(rect, "H", cut)
            keep_lo = fy == 0
        other = _grow(rng, rh if keep_lo else rl)
        lo = inner_node if keep_lo else other
        hi = other if keep_lo else inner_node
        return _mk_node(rect, axis, cut, lo, hi)

    if rng.random() < 0.5:
        band = isolate((fx, 0, fx + 40, CANVAS), "H", frame_node)
        tree = isolate((0, 0, CANVAS, CANVAS), "V", band)
    else:
        band = isolate((0, fy, CANVAS, fy + 40), "V", frame_node)
        tree = isolate((0, 0, CANVAS, CANVAS), "H", band)

    bg_name, bg_rgb = _pick_bg(rng)
    _apply_bg(tree, bg_rgb)
    frame_info = {
        "color": frame_color,
        "rgb": list(frame_rgb),
        "rect": list(frect),
        "inner": list(inner["rect"]),
    }
    return Scene(
        idx=idx,
        tier=3,
        tree=tree,
        objects=[obj],
        background=bg_name,
        frame=frame_info,
    )


_BUILDERS = {0: _build_tier0, 1: _build_tier1, 2: _build_tier2, 3: _build_tier3}


# --------------------------------------------------------------------------
# public API
# --------------------------------------------------------------------------

def sample_scene(
    global_seed: int,
    idx: int,
    tier: Optional[int] = None,
    tier_mix: Sequence[float] = DEFAULT_TIER_MIX,
) -> Scene:
    """Deterministically sample scene `idx` under `global_seed`.

    If `tier` is None it is drawn from `tier_mix` (first rng draw, so the
    scene is a pure function of (global_seed, idx, tier or tier_mix)).
    """
    rng = scene_rng(global_seed, idx)
    if tier is None:
        p = np.asarray(tier_mix, dtype=np.float64)
        p = p / p.sum()
        tier = int(rng.choice(4, p=p))
    return _BUILDERS[int(tier)](rng, int(idx))
